"""about author

Revision ID: 061327190d9d
Revises: 6b9bf3e5c5f2
Create Date: 2022-08-05 09:24:07.673798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061327190d9d'
down_revision = '6b9bf3e5c5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('about_author', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'about_author')
    # ### end Alembic commands ###
