"""added profile pic

Revision ID: 86c7cffe1329
Revises: f90a2c9c159c
Create Date: 2022-08-08 18:10:26.975324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c7cffe1329'
down_revision = 'f90a2c9c159c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('profile_pic_db', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'profile_pic_db')
    # ### end Alembic commands ###
