"""profile pic

Revision ID: f90a2c9c159c
Revises: 061327190d9d
Create Date: 2022-08-08 18:08:42.194710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90a2c9c159c'
down_revision = '061327190d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('profile_pic_db', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'profile_pic_db')
    # ### end Alembic commands ###
